enabled = "yes"

[settings]
#name="example3"
url_prefix = "/example3"
template_folder = "templates"
static_folder = "static"
#static_url_path = "/exmaple_blueprint/static"

[session]
var_in_session = "this can be loaded using fl_bp.session"
permissions = ["this", "that"]
logged_in = true
not_logged_in = false
